config/routes.rb
Rails.application.routes.draw do
  root "pages#index"
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]
 # resources :listings
  resources :listings do
    resources :bookings
  end

  resources :bookings do
    resources :braintree, only: [:new]
  end

  resources :users, controller: "users" do
    resources :bookings
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  get "users/:id/username" => "users#username", as: "create_username"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get "tags/:tag", to: "pages#index", as: :tag
  post 'braintree/checkout'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/braintree_controller.rb
class BraintreeController < ApplicationController
  def new
  	@booking = Booking.find(params[:booking_id])
  	@listing = @booking.listing
  	@price = @booking.price(@listing)
  	@client_token = Braintree::ClientToken.generate
  end

  def checkout
	  nonce_from_the_client = params[:checkout_form][:payment_method_nonce]
	  @booking = Booking.find(params[:checkout_form][:booking_id])
  	@listing = @booking.listing
  	price = @booking.price(@listing)

	  result = Braintree::Transaction.sale(
	   :amount => price,
	   :payment_method_nonce => nonce_from_the_client,
	   :options => {
	      :submit_for_settlement => true
	    }
	   )

	  if result.success?
	    redirect_to :root, :flash => { :success => "Transaction successful!" }
	    NewBookingJob.perform_later(@listing.user, @booking.user, @booking)
	  else
	    redirect_to :root, :flash => { :error => "Transaction failed. Please try again." }
	  end 
	end
end

app/helpers/braintree_helper.rb
module BraintreeHelper
end

app/views/braintree/new.html.erb
<h1>Make Payment</h1>

<p> <%= @price %> </p>

<%= form_for :checkout_form, url: braintree_checkout_path, html: { id: "cardForm"} do |form| %>
	
  <%= form.label :card_number, "Credit/Debit Card Number", html: {class: "hosted-fields--label"} %>
  <div id="card-number" class="hosted-field"></div>

  <%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>      
  <div id="expiration-date" class="hosted-field"></div>

  <%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"} %>
  <div id="cvv" class="hosted-field"></div>

  <%= form.hidden_field "booking_id", value: @booking.id %>

  <%= form.hidden_field "payment_method_nonce" %>

  <div class="button-container">
    <%= form.submit "Purchase", disabled: true, class: "button", id: "submit-payment" %>
  </div>
<% end %>

<!-- Load the Client component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/client.min.js"></script>

<!-- Load the Hosted Fields component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js"></script>

<script>

	var form = document.querySelector('#cardForm');
	var submit = document.querySelector("#submit-payment");

	braintree.client.create({
	  // Replace this with your own authorization.
	  authorization: '<%= @client_token %>'
	}, function (clientErr, clientInstance) {
	  if (clientErr) {
	    // Handle error in client creation
	    return;
	  }

	  braintree.hostedFields.create({
	    client: clientInstance,
	    styles: {
	      'input': {
	        'font-size': '14pt'
	      },
	      'input.invalid': {
	        'color': 'red'
	      },
	      'input.valid': {
	        'color': 'green'
	      }
	    },
	    fields: {
	      number: {
	        selector: '#card-number',
	        placeholder: '4111 1111 1111 1111'
	      },
	      cvv: {
	        selector: '#cvv',
	        placeholder: '123'
	      },
	      expirationDate: {
	        selector: '#expiration-date',
	        placeholder: '10/2019'
	      }
	    }
	  }, function (hostedFieldsErr, hostedFieldsInstance) {
	    if (hostedFieldsErr) {
	      // Handle error in Hosted Fields creation
	      return;
	    }

	    submit.removeAttribute('disabled');

	    form.addEventListener('submit', function (event) {
	      event.preventDefault();

	      hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
	        if (tokenizeErr) {
	          // Handle error in Hosted Fields tokenization
	          return;
	        }

	        // Put `payload.nonce` into the `payment_method_nonce` input, and then
	        // submit the form. Alternatively, you could send the nonce to your server
	        // with AJAX.
	        document.querySelector('input[name="checkout_form[payment_method_nonce]"]').value = payload.nonce;
	        form.submit();
	      });
	    }, false);
	  });
	});

</script>