config/routes.rb
Rails.application.routes.draw do
  root "pages#index"
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]
 # resources :listings
  resources :listings do
    resources :bookings
  end

  resources :bookings do
    resources :braintree, only: [:new]
  end

  resources :users, controller: "users" do
    resources :bookings
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  get "users/:id/username" => "users#username", as: "create_username"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get "tags/:tag", to: "pages#index", as: :tag
  post 'braintree/checkout'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
class Listing < ApplicationRecord
	belongs_to	:user
	has_many :bookings, :dependent => :destroy
	acts_as_taggable
	acts_as_taggable_on :amenities
	mount_uploaders :images, ImageUploader
	scope :room_type, -> (room_type) { where room_type: room_type }
	
	def self.search(search)
		if search
			where(["city_town ILIKE ?", "%#{search}%"]).or(where(["state_county ILIKE ?", "%#{search}%"])).or(where(["country ILIKE ?", "%#{search}%"]))
		else
			all
		end
	end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :find_listing, only: [:show,:update,:edit,:destroy]
	def new
    @listing = Listing.new
  end

  def create
    @listing = current_user.listings.new(listing_params)
    if @listing.save
      redirect_to @listing
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    @listing.update(listing_params)
    redirect_to @listing
  end

  def destroy
    @listing.destroy
    redirect_to root_path
  end

  private

  def find_listing
    @listing = Listing.find(params[:id])
  end

  def listing_params
    params.require(:listing).permit(:title, :description, :price_per_night, :room_type, :property_type, :guest_num, :bedroom_num, :bed_num, :bathroom_num, :address_line_one, :address_line_two, :city_town, :state_county, :country, :zip_postcode, :tag_list => [], :amenity_list => [], :images => [])
  end

end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<div class="text-field">
  <%= form.text_field :title %>
</div>

<div class="text-field">
  <%= form.text_area :description%>
</div>

<div class="price-field">
  <%= form.number_field :price_per_night%>
</div>

<div class="text-field">
  <%= form.text_field :room_type %>
</div>

<div class="text-field">
  <%= form.text_field :property_type %>

<div class="number-field">
  <%= form.number_field :guest_num, label: "Maximum Guests"%>
</div>

<div class="number-field">
  <%= form.number_field :bedroom_num, label: "Number of Bedrooms"%>
</div>

<div class="number-field">>
  <%= form.number_field :bed_num, label: "Number of Beds"%>
</div>

<div class="number-field">
  <%= form.number_field :bathroom_num, label: "Number of Bathrooms"%>
</div>

<div class="text-field">
  <%= form.text_field :address_line_one %>
</div>

<div class="text-field">
  <%= form.text_field :address_line_two %>
</div>

<div class="text-field">
  <%= form.text_field :city_town, label: "Town/City" %>
</div>

<div class="text-field">
  <%= form.text_field :state_county, label: "State/Province/County" %>
</div>

<div class="text-field">
  <%= form.text_field :country %>
</div>

<div class="text-field">
  <%= form.text_field :zip_postcode, label: "Zip/Postcode" %>
</div>

<div class="checkbox-fields">
  Amenities</br>
  <%= form.check_box :amenity_list, { multiple: true, label: "Washing machine" }, 'Washing machine', nil %>
  <%= form.check_box :amenity_list, { multiple: true, label: "Swimming pool" }, 'Swimming pool', nil %>
  <%= form.check_box :amenity_list, { multiple: true, label: "WiFi" }, 'WiFi', nil %>
  <%= form.check_box :amenity_list, { multiple: true, label: "Kitchen" }, 'Kitchen', nil %>
</div>

<div class="field">
  <%= form.file_field :images, multiple: true %>
</div>

app/views/listings/edit.html.erb
<h1>Edit this listing</h1>

<%= form_for @listing do |form| %>
  <%= render partial: '/listings/form', object: form %>

	<div class="submit-field">
	  <%= form.submit %>
	</div>
<% end %>

app/views/listings/new.html.erb
  <div id="errors"></div>

  <%= bootstrap_form_for @listing, remote: true do |form| %>
    <%= render partial: '/listings/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>
  <% end %>

app/views/listings/show.html.erb
<h1><%= @listing.title %></h1>
<% if @listing.images.present? %>
	<% @listing.images_urls(:listing_page).each do |img| %>
		<%= image_tag img %>
	<% end %>		
<% end %>	

<p><%= @listing.description %></p>

<p>Price: £<%= @listing.price_per_night %></p>

<p>Room Type: <%= @listing.room_type %></p>

<p>Property Type: <%= @listing.property_type %></p>

<p>Guests: <%= @listing.guest_num %> Bedrooms: <%= @listing.bedroom_num %> Beds: <%= @listing.bed_num %> Baths: <%= @listing.bathroom_num %></p>

<p>Location: <%= @listing.city_town %>, <%= @listing.state_county %>, <%= @listing.country %></p>

<p>Amenities</br> <ul>
<% @listing.amenity_list.each do |amenity| %>
  <li><%= amenity %></li>
<% end %>
</ul>
</p>

<%= link_to 'Book now', new_listing_booking_path(@listing) %>

<% if @listing.user_id == current_user.id || current_user.email == "emily.kennedy_95@hotmail.co.uk" %>
<%= link_to 'Edit this listing', edit_listing_path(@listing) %>

<%= link_to 'Delete', listing_path(@listing),data: {:confirm => 'Are you sure?'}, :method => :delete %>
<% end %>