config/routes.rb
Rails.application.routes.draw do
  root "pages#index"
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]
 # resources :listings
  resources :listings do
    resources :bookings
  end

  resources :bookings do
    resources :braintree, only: [:new]
  end

  resources :users, controller: "users" do
    resources :bookings
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  get "users/:id/username" => "users#username", as: "create_username"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get "tags/:tag", to: "pages#index", as: :tag
  post 'braintree/checkout'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :listing
  validate :availability

  def availability
  	listing.bookings.each do |existing|
  		if overlap?(self, existing)
  			errors.add(:property_unavailable, "on the dates you have have requested")
  		end
  	end
  end

  def overlap?(x,y)
  (x.check_in - y.check_out) * (y.check_in - x.check_out) > 0
	end

  def price(listing)
    days = self.check_out - self.check_in
    (days * listing.price_per_night).to_i
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
	def new
		@booking = Listing.find(params[:listing_id]).bookings.new
		@listing = Listing.find(params[:listing_id])
	end

  def create
  	@booking = current_user.bookings.new(booking_params)
  	@booking.listing_id = params[:listing_id]
  	@listing = Listing.find(params[:listing_id])
  	if @booking.save
      redirect_to new_booking_braintree_path(@booking)
    else
    	@errors = @booking.errors.full_messages
      render 'new'
    end
  end


	private
	def booking_params
    params.require(:booking).permit(:check_in, :check_out)
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<div class="field">
  <%= form.label :check_in %>
  <%= form.date_field :check_in, id: "check_in" %>
</div>

<div class="field">
  <%= form.label :check_out %>
  <%= form.date_field :check_out, id: "check_out"%>
</div>

<div id="price" data-per-night = <%= price %> >
£0.00
</div>
<script>
$("form").change(function() {
	var check_in_date = new Date(($("#check_in").val()))
	var check_out_date = new Date(($("#check_out").val()))
	var difference = (check_out_date - check_in_date)/1000/60/60/24
	if (difference > 0) {
		$("#price").html("£" + (Number($("#price").data("per-night"))*difference).toFixed(2));
	}
})
</script>

app/views/bookings/new.html.erb
<% if @errors.present? %>	
	<ul>
	<% @errors.each do |msg| %>
	  <li><%= msg %></li>
	<% end %>
	</ul>
	</br>
<% end %>

<%= form_for @booking, url: listing_bookings_path do |form| %>
  <%= render partial: '/bookings/form', object: form, locals: {price: @listing.price_per_night.to_f} %>

  <div class="submit-field">
    <%= form.submit "Proceed to Payment" %>
  </div>
<% end %>