config/routes.rb
Rails.application.routes.draw do
  root "pages#index"
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]
 # resources :listings
  resources :listings do
    resources :bookings
  end

  resources :bookings do
    resources :braintree, only: [:new]
  end

  resources :users, controller: "users" do
    resources :bookings
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  get "users/:id/username" => "users#username", as: "create_username"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get "tags/:tag", to: "pages#index", as: :tag
  post 'braintree/checkout'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">

			<a id="menu-toggle" href="#" class="nav-btn btn-dark btn-lg toggle">
				<i class="fa fa-bars" style="color:#fff;"></i>
			</a>
			<a id="to-top" class="btn btn-lg btn-inverse" href="#top">
				<span class="sr-only">Toggle to Top Navigation</span>
				<i class="fa fa-chevron-up"></i>
			</a>
		</div>
		<!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse js-navbar-collapse">
        		<ul class="nav navbar-nav navbar-left">
        			<a class="navbar-brand" href="/">
        						<img height="20" width="20" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAB+0lEQVR4AcyYg5LkUBhG+1X2PdZGaW3btm3btm3bHttWrPomd1r/2Jn/VJ02TpxcH4CQ/dsuazWgzbIdrm9dZVd4pBz4zx2igTaFHrhvjneVXNHCSqIlFEjiwMyyyOBilRgGSqLNF1jnwNQdIvAt48C3IlBmHCiLQHC2zoHDu6zG1iXn6+y62ScxY9AODO6w0pvAqf23oSE4joOfH6OxfMoRnoGUm+de8wykbFt6wZtA07QwtNOqKh3ZbS3Wzz2F+1c/QJY0UCJ/J3kXWJfv7VhxCRRV1jGw7XI+gcO7rEFFRvdYxydwcPsVsC0bQdKScngt4iUTD4Fy/8p7PoHzRu1DclwmgmiqgUXjD3oTKHbAt869qdJ7l98jNTEblPTkXMwetpvnftA0LLHb4X8kiY9Kx6Q+W7wJtG0HR7fdrtYz+x7iya0vkEtUULIzCjC21wY+W/GYXusRH5kGytWTLxgEEhePPwhKYb7EK3BQuxWwTBuUkd3X8goUn6fMHLyTT+DCsQdAEXNzSMeVPAJHdF2DmH8poCREp3uwm7HsGq9J9q69iuunX6EgrwQVObjpBt8z6rdPfvE8kiiyhsvHnomrQx6BxYUyYiNS8f75H1w4/ISepDZLoDhNJ9cdNUquhRsv+6EP9oNH7Iff2A9g8h8CLt1gH0Qf9NMQAFnO60BJFQe0AAAAAElFTkSuQmCC" class="img-responsive pull-left" alt="Responsive image">
        					 PairBnB</a>
                    <li class="dropdown mega-dropdown">
            			<a href="#" class="dropdown-toggle" data-toggle="dropdown">Women <span class="caret"></span></a>				
        				<ul class="dropdown-menu mega-dropdown-menu">
        					<li class="col-sm-3">
            					<ul>
        							<li class="dropdown-header">Features</li>
        							<li><a href="#">Auto Carousel</a></li>
                                    <li><a href="#">Carousel Control</a></li>
                                    <li><a href="#">Left & Right Navigation</a></li>
        							<li><a href="#">Four Columns Grid</a></li>
        							<li class="divider"></li>
        							<li class="dropdown-header">Fonts</li>
                                    <li><a href="#">Glyphicon</a></li>
        							<li><a href="#">Google Fonts</a></li>
        						</ul>
        					</li>
        					<li class="col-sm-3">
        						<ul>
        							<li class="dropdown-header">Plus</li>
        							<li><a href="#">Navbar Inverse</a></li>
        							<li><a href="#">Pull Right Elements</a></li>
        							<li><a href="#">Coloured Headers</a></li>                            
        							<li><a href="#">Primary Buttons & Default</a></li>							
        						</ul>
        					</li>
        					<li class="col-sm-3">
        						<ul>
        							<li class="dropdown-header">Much more</li>
                                    <li><a href="#">Easy to Customize</a></li>
        							<li><a href="#">Calls to action</a></li>
        							<li><a href="#">Custom Fonts</a></li>
        							<li><a href="#">Slide down on Hover</a></li>                         
        						</ul>
        					</li>
                            <li class="col-sm-3">
            					<ul>
        							<li class="dropdown-header">Women Collection</li>                            
                        <div id="womenCollection" class="carousel slide" data-ride="carousel">
                          <div class="carousel-inner">
                            <div class="item active">
                                <a href="#"><img src="http://placehold.it/254x150/3498db/f5f5f5/&text=New+Collection" class="img-responsive" alt="product 1"></a>
                                <h4><small>Summer dress floral prints</small></h4>                                        
                                <button class="btn btn-primary" type="button">49,99 €</button> <button href="#" class="btn btn-default" type="button"><span class="glyphicon glyphicon-heart"></span> Add to Wishlist</button>       
                            </div><!-- End Item -->
                            <div class="item">
                                <a href="#"><img src="http://placehold.it/254x150/ff3546/f5f5f5/&text=New+Collection" class="img-responsive" alt="product 2"></a>
                                <h4><small>Gold sandals with shiny touch</small></h4>                                        
                                <button class="btn btn-primary" type="button">9,99 €</button> <button href="#" class="btn btn-default" type="button"><span class="glyphicon glyphicon-heart"></span> Add to Wishlist</button>        
                            </div><!-- End Item -->
                            <div class="item">
                                <a href="#"><img src="http://placehold.it/254x150/2ecc71/f5f5f5/&text=New+Collection" class="img-responsive" alt="product 3"></a>
                                <h4><small>Denin jacket stamped</small></h4>                                        
                                <button class="btn btn-primary" type="button">49,99 €</button> <button href="#" class="btn btn-default" type="button"><span class="glyphicon glyphicon-heart"></span> Add to Wishlist</button>      
                            </div><!-- End Item -->                                
                          </div><!-- End Carousel Inner -->
                          <!-- Controls -->
                          <a class="left carousel-control" href="#womenCollection" role="button" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                          </a>
                          <a class="right carousel-control" href="#womenCollection" role="button" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                          </a>
                        </div><!-- /.carousel -->
                        <li class="divider"></li>
                        <li><a href="#">View all Collection <span class="glyphicon glyphicon-chevron-right pull-right"></span></a></li>
        						</ul>
        					</li>
        				</ul>				
        			</li>
              <li><a href="#">Store locator</a></li>
        		</ul>
                <ul class="nav navbar-nav navbar-right">
                <% if signed_in? %>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">My account <span class="caret"></span></a>
                      <ul class="dropdown-menu" role="menu">
                        <li><a href="#">Action</a></li>
                        <li><%= link_to "Edit your details", edit_user_path(current_user) %></li>

                        <li class="divider"></li>
                        <li><%= link_to 'Sign out', sign_out_path, method: :delete %></li>
                      </ul>
                    </li>
                    <li><%= link_to 'Create a new listing', new_listing_path %></li>
                  <% else %>
                    <li> <%= link_to 'Sign in', sign_in_path %></li>
                    <li> <%= link_to "Sign in with Facebook", "/auth/facebook" %></li>
                  <% end %>
                <li><a href="#">My cart (0) items</a></li>
              </ul>
        	</div><!-- /.nav-collapse -->
	</div><!-- /.container-fluid -->
</nav>
<nav id="sidebar-wrapper">
	<ul class="sidebar-nav">
		<a id="menu-close" href="#" class="btn btn-danger pull-right hidden-md hidden-lg toggle"><i class="fa fa-times"></i></a>
		<li class="sidebar-brand">
			<a href="#top">Soldier-up <strong>Designs</strong></a>
		</li>
		<li>
			<a href="/" title="Go to Top">Home</a>
		</li>
		<li>
			<a href="/about" title="Go to About Us section">About</a>
		</li>
		<li>
			<a href="/resume" title="Navigate to Jonathan Adcox IT Resume">Resume</a>
		</li>
		<li>
			<a href="/portfolio" title="Navigate to 'Our Services' section">Portfolio</a>
		</li>
		<!-- Future Development
		<li>
			<a href="#portfolio">Portfolio</a>
		</li> -->
		<li>
			<a href="/blog" title="Our Blog">Blog</a>
		</li>
		<li>
			<a data-toggle="modal" data-href="#loginModal" data-target="#loginModal" style="cursor:pointer;"> Hosting</a>
		</li>
	</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PairBnB</title>
    <%= csrf_meta_tags %>
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "layouts/navbar" %>
  	<div class="container">
		  <% if signed_in? %>
	  		<% if current_user.avatar.present? %>
	  			<%= image_tag current_user.avatar_url(:header) %>
	  		<% end %>	
		    Signed in as: <%= current_user.username %>
		    <%= link_to 'Create a new listing', new_listing_path %>
		    <%= link_to "Edit your details", edit_user_path(current_user) %>
		    <%= button_to 'Sign out', sign_out_path, method: :delete %>
		  <% else %>
		    <%= link_to 'Sign in', sign_in_path %>
		    <%= link_to "Sign in with Facebook", "/auth/facebook" %>
		  <% end %>

		  <div id="flash">
		    <% flash.each do |key, value| %>
		      <div class="flash <%= key %>"><%= value %></div>
		    <% end %>
		  </div>
	    <%= yield %>
    </div>
  </body>
</html>